services:
  web:
    build:
      dockerfile: ./packages/web-server/Dockerfile
      context: .
    ports:
      - 9998:9998

  back:
    build:
      dockerfile: ./packages/back-server/Dockerfile
      context: .
    ports:
      - 9999:9999